#pragma once
#include "Renderer/Types.hpp"
#include <vulkan/vulkan.h>

VkFormat GetVulkanImageFormat(ImageFormat imageFormat);
VkImageLayout GetVulkanImageLayout(ImageLayout imageLayout);
VkImageUsageFlags GetVulkanImageUsage(ImageUsage imageUsage);
VkBufferUsageFlags GetVulkanBufferUsage(BufferUsage bufferUsage);
VkImageAspectFlags GetVulkanImageAspect(ImageAspect imageAspect);
VkAttachmentLoadOp GetVulkanLoadOperation(LoadOperation loadOperation);
VkAttachmentStoreOp GetVulkanStoreOperation(StoreOperation storeOperation);
VkDescriptorType GetVulkanDescriptorType(DescriptorType descriptorType);
VkPipelineStageFlags GetVulkanPipelineStage(PipelineStage pipelineStage);
VkShaderStageFlags GetVulkanShaderStage(ShaderStage shaderStage);
VkSampleCountFlagBits GetVulkanSampleCount(SampleCount sampleCount);
VkMemoryPropertyFlags GetVulkanMemoryProperty(MemoryProperty memoryProperty);
VkPhysicalDeviceType GetVulkanDeviceType(DeviceType deviceType);
VkFilter GetVulkanFilter(Filter filter);
VkSamplerAddressMode GetVulkanAddressMode(AddressMode addressMode);
VkPresentModeKHR GetVulkanPresentMode(PresentMode presentMode);
VkFrontFace GetVulkanFrontsFace(FrontFace face);
VkPrimitiveTopology GetVulkanPrimitive(PrimitiveType primitive);
VkCullModeFlags GetVulkanCullMode(CullMode mode);
VkVertexInputRate GetVulkanInputRate(InputRate inputRate);
VkPipelineBindPoint GetVulkanPipelineBindPoint(PipelineBindPoint bindPoint);
VkColorSpaceKHR GetVulkanColorSpace(ColorSpace colorspace);
VkImageViewType GetVulkanViewType(ViewType viewtype);
VkImageType GetVulkanImageType(ImageType type);
VkComponentSwizzle GetVulkanComponentSwizzle(ComponentSwizzle swizzle);
VkCompareOp GetVulkanCompareType(CompareType compare);

ImageFormat GetNativeImageFormat(VkFormat imageFormat);
ImageLayout GetNativeImageLayout(VkImageLayout imageLayout);
ImageUsage GetNativeImageUsage(VkImageUsageFlags imageUsage);
BufferUsage GetNativeBufferUsage(VkBufferUsageFlags bufferUsage);
ImageAspect GetNativeImageAspect(VkImageAspectFlags imageAspect);
LoadOperation GetNativeLoadOperation(VkAttachmentLoadOp loadOperation);
StoreOperation GetNativeStoreOperation(VkAttachmentStoreOp storeOperation);
DescriptorType GetNativeDescriptorType(VkDescriptorType descriptorType);
PipelineStage GetNativePipelineStage(VkPipelineStageFlags pipelineStage);
ShaderStage GetNativeShaderStage(VkShaderStageFlags shaderStage);
SampleCount GetNativeSampleCount(VkSampleCountFlagBits sampleCount);
MemoryProperty GetNativeMemoryProperty(VkMemoryPropertyFlags memoryProperty);
DeviceType GetNativeDeviceType(VkPhysicalDeviceType deviceType);
Filter GetNativeFilter(VkFilter filter);
AddressMode GetNativeAddressMode(VkSamplerAddressMode addressMode);
PresentMode GetNativePresentMode(VkPresentModeKHR presentMode);
FrontFace GetNativeFrontsFace(VkFrontFace face);
PrimitiveType GetNativePrimitive(VkPrimitiveTopology primitive);
CullMode GetNativeCullMode(VkCullModeFlags mode);
InputRate GetNativeInputRate(VkVertexInputRate inputRate);
PipelineBindPoint GetNativePipelineBindPoint(VkPipelineBindPoint bindPoint);
ColorSpace GetNativeColorSpace(VkColorSpaceKHR colorspace);
ViewType GetNativeViewType(VkImageViewType viewtype);
ImageType GetNativeImageType(VkImageType type);
ComponentSwizzle GetNativeComponentSwizzle(VkComponentSwizzle swizzle);
CompareType GetNativeCompareType(VkCompareOp compare);
